services:
  api:
    build:
      context: ./apps/api
      dockerfile: dockerfile
    container_name: apps_api
    ports:
      - "5000:5000"
    volumes:
      - ./apps/api:/app
      - api_node_modules:/app/node_modules

  web:
    build:
      context: ./apps/web
      dockerfile: dockerfile
      target: development
    container_name: apps_web
    ports:
      - "3000:3000"
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - ./apps/web:/app
      - web_node_modules:/app/node_modules

volumes:
  api_node_modules:
  web_node_modules:
